title: Qifa Primary School
url: https://qifapri.moe.edu.sg
favicon: /images/Main Images/school_logo_icon.png
colors:
  primary-color: "#276885"
  secondary-color: "#ffffff"
  media-colors:
    - title: media-color-one
      color: "#276885"
    - title: media-color-two
      color: "#276885"
    - title: media-color-three
      color: "#276885"
    - title: media-color-four
      color: "#276885"
    - title: media-color-five
      color: "#276885"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1i3m52bw81st9.amplifyapp.com
prod: https://master.d1i3m52bw81st9.amplifyapp.com
shareicon: /images/logo-main.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
